#!/bin/bash -l
#PBS -l nodes=11:ppn=8
#PBS -l walltime=01:00:00
#PBS -j oe
#PBS -N Mastermind
#PBS -o mastermind_out.txt

echo "Running job..."

module load OpenMPI/3.1.4-GCC-8.3.0

cd $HOME

mpiCC *.cpp *.h -o mastermind -std=c++11

mpirun -np 7 mastermind 4

echo "Done"
