//
// Created by Madalin Ionescu on 2019-12-07.
//

#ifndef RTOS_MASTERMIND_PLAYER_H
#define RTOS_MASTERMIND_PLAYER_H

#include <vector>
#include <cstdlib>
#include <iostream>

using namespace std;
using nat = unsigned;


class Player {

private:
    nat colors;
    nat positions;

    void generatePosition(nat* proposal, nat position, const vector<nat*> *previousGuesses, const vector<nat*> *previousEvaluations);

public:
    Player() = default;
    Player(nat colors, nat positions);

    nat* pickFirstSolution();

    // function used to analyze the context before launching the threads to find
    // the new solution proposition
    vector<nat*> analyzeContext(vector<nat*> previousPropositions);

    // picks randomly one of the solutions generated by a processor
    nat* pickSolution();

    bool proposalIsDifferent(const nat* proposal, nat proposalLen, const nat* reference) const;

    bool proposalRespectsKnowledge(const nat* proposal, nat proposalLen, const nat* reference, const nat* referenceScore) const;

    bool plausibleSolution(const vector<nat*> *previousGuesses, const vector<nat*> *previousEvaluations, const nat* solution, nat solLen) const;

    nat* generatePlausibleSolution(nat fixedPositions, const nat* posList, const vector<nat*> *previousGuesses, const vector<nat*> *previousEvaluations);
};


#endif //RTOS_MASTERMIND_PLAYER_H
