//
// Created by Madalin Ionescu on 2019-12-07.
//

#ifndef RTOS_MASTERMIND_PLAYER_H
#define RTOS_MASTERMIND_PLAYER_H

using nat = unsigned;


class Player {

    public Player(nat colors, nat positions);

    // function used to analyze the context before launching the threads to find
    // the new solution proposition
    public nat* analyzeContext(nat* previousPropositions);

    // picks randomly one of the solutions generated by a processor
    public nat* pickRandom();
};


#endif //RTOS_MASTERMIND_PLAYER_H
